{% set name = "tlslite" %}
{% set version = "0.4.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b9a487694c239efea8cec4454a99a56ee1ae1a5f3af0858ccf8029e2ac2d42d

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [py>36]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tlslite
    - tlslite.integration
    - tlslite.utils

about:
  home: http://trevp.net/tlslite/
  license: Public Domain and BSD 3-Clause
  summary: 'tlslite implements SSL and TLS.'

extra:
  recipe-maintainers:
    - pmlandwehr
