# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lSUcMl3DLmN4ByQQyRNUTi1g+Ryc4+uB64qsKWv7KPozhZdt2d/WykivpHOgXPW4dLtUGqY3J+qGa169kinlWGM9F5YPg/8jSEiZjhSXd4Q54hK7LgBB1QIa1tspEGlNFADPL/Ex0X9fPXADC0yVk+/7ZhU097dtZMdBp68LGLtZVMT0hL5n+YhLU8RPFaccACLwjgYnXNl0jnnKDTFAzm+a6YtI4JIDWOVSMa/bLUsPhxB3du+nbASYDkyx1xhIJsryoA6/NSMuwxqoNb1hVpDWxZHlEMvo2DFp0SOthh/aeMRMI7UudI74pAkLcgy3nBLh6UHq+xqJEiylSo7MMAqgIpoVPiCEs6cGFbvCxpHV8gkuEKOm2uQNkFnLAKwAKKdsAs+/CteR+8DX04WK0dhrd1o+a7z1H/7C6/eATIL6duULIJkStk5BpTnfrDH38efHodxCg3s7TyRpBOH6bRVRdri+z3Dpf3OJx8ltDJljv7lTEF+jG9+11tH1qmfctvgjqlEpqIu8NxqVhsfdOT9VixP5lV/ty57e/MetmzPVNsADcE8y37NrgOcs3pNHZalKJ0Ox/GQVY0nsyxUILO3cBgHoCk7MwhBj1NxLBDeH8K4zY41DyYeteD0KtgnWh/hrE+f3iQNXnj99rf+CRtZmfRlsTa//NGy17kSR9hA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
