# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Hsbs6iaD7LFSz+3EywVF2XI1DMy/4D956QsPnUfjKaUYWi/CCw1CUHzbyqtVaKGqfR/YMnbLQ0+sYJ+6II43ywC+aJ/BD10QBPU9NSHzuNuoFJkF4jLpC+Ji/cfN3yd7o2lPOD72PgSSNCc67LTnmKJuC8CgQull31MPmN6kWEUexLa9JIkJ1uNWu6BWZp8rBadWeQViOnhyCUcpHouDoQoOT/80aEWRnEh6PlqFCguIintZkrsSCRRwgicIiIsbwN36/iGdC+F9YumSZSzXhGjV8e5IJJrEz59nuZG/2V52GfN2+6E5nznJykGtPbckWemZYM09yljBbwRFLZgP/a/y92+ycNBu9Ca4B3j2HhBkzU5Uj3vnTjANRm4kgwOr9aZCGmaC2/1Uigd4bv+iSUs0M5dx/DSiNbLF+gU/nCCSFvPMTWCDqhxv8DlLQ1omvWJP62NRrCRvJxVU17xzAvrIjeQZTIQaJD5SKXMIOenLhM9hiV8eF2d9a3TjwQEJMzNAe6Juq5wS6ByuKUtehWPpunqu8+A/Bly+ySHO+l1Cu5fCTHC2G4qI9PTclWsZPPql8cSzFdQLcqKg73GzTW1e7Lzz7fOK/JipOYopCfAC8IEMkqhQCACr73PZeEkpti7fpJstN1GtbHV/1a9sHmR7F+AR8KpmFMA/V/Y8AO0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
