appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Hsbs6iaD7LFSz+3EywVF2XI1DMy/4D956QsPnUfjKaUYWi/CCw1CUHzbyqtVaKGqfR/YMnbLQ0+sYJ+6II43ywC+aJ/BD10QBPU9NSHzuNuoFJkF4jLpC+Ji/cfN3yd7o2lPOD72PgSSNCc67LTnmKJuC8CgQull31MPmN6kWEUexLa9JIkJ1uNWu6BWZp8rBadWeQViOnhyCUcpHouDoQoOT/80aEWRnEh6PlqFCguIintZkrsSCRRwgicIiIsbwN36/iGdC+F9YumSZSzXhGjV8e5IJJrEz59nuZG/2V52GfN2+6E5nznJykGtPbckWemZYM09yljBbwRFLZgP/a/y92+ycNBu9Ca4B3j2HhBkzU5Uj3vnTjANRm4kgwOr9aZCGmaC2/1Uigd4bv+iSUs0M5dx/DSiNbLF+gU/nCCSFvPMTWCDqhxv8DlLQ1omvWJP62NRrCRvJxVU17xzAvrIjeQZTIQaJD5SKXMIOenLhM9hiV8eF2d9a3TjwQEJMzNAe6Juq5wS6ByuKUtehWPpunqu8+A/Bly+ySHO+l1Cu5fCTHC2G4qI9PTclWsZPPql8cSzFdQLcqKg73GzTW1e7Lzz7fOK/JipOYopCfAC8IEMkqhQCACr73PZeEkpti7fpJstN1GtbHV/1a9sHmR7F+AR8KpmFMA/V/Y8AO0=}
conda_forge_output_validation: false
