travis:
  secure:
    BINSTAR_TOKEN: UqNbQulynJaRQUzKkvYydOaijsMCNB84YhNi8qmHQPPnBEBBRinqCWR5ow+AnwFqNLKjKwepAe/J/BjKVk1g6IJ367M93+QMm+jkcSFNrGS2QHvq7dUoGdyqx/CdfhCkBjCCGeWj4gJD3IfqGf+PwgmQSspn+f1YFUEroS9/2OSAMnIeNN55R6rJl9+cV2+3WbaDxk17/Qq1kg3CzMI/5UqDa6oWu+eDX7ePppTgIuco0iZ43ENodu9a5BkpmP9V3p5NvPeViIvNGYgIjvnbjKG8JSz8qtZRGN7rsuOhYRf7vhki60zVTeFOmj1lEPrL9mjFCgqpyzzahNf5RqPSXQwlq3DQBt2rseq855u6d9U73DWvmKS5/JMoPR+sc9sRfvpOPRzpPWBIZQYU37ip1yFJ47DVkvl/KcKUzUswGtcR1F4l24CyhdR1ivCV3kSjszCLR4WJNgYi9CJyzr65XlK9txXB5OsQ5FEiu9Kf/9JUg5R5Q5YRmMt+3ShD9BLxMe/O0rQfvdVPg0+dYqUaW1t2FaAILZsDb8YNtmB0PXcIIX4D6tyk80LmRszfbnrDmZho9qOlhrpqqabxwiq+9PsO0sB8Qyr/1omaNqK7bUWqln7TY2A3KFM4pELN5ZRkGFx2DVMUfOyzCSkamCG5vNluqSV/ReF+d3h9TY6wAwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
